name: R
channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::jupyter_client
- conda-forge::r-irkernel
- conda-forge::r-janitor=2.2.*
- conda-forge::r-svglite=2.1.*
- conda-forge::r-tidyverse=2.0.*
- bioconda::bioconductor-multtest=2.58.*

# only package to install in R with `install.packages()`: asreml v4.2
